spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/neha
    username: postgres
    password: neha1811
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect